### ISSUE TITLE
9 peaks for RCP-30-5A

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#134] opened 2018-01-21 00:58 UTC
"Bead peaks identified as 7 to 9 of 8"
![bead-calibration](https://user-images.githubusercontent.com/28678480/35189608-5171274e-fe1c-11e7-8949-99939c4d218c.png)

**Comment by mjbrenner** [comment] 2018-01-21 01:07
I am experiencing this issue as well.
"Bead peaks identified as 4 to 7 of 6"
![bead-calibration](https://user-images.githubusercontent.com/31046613/35189657-93ec7e38-fe1d-11e7-8e4d-eb88ce020236.png)

**Comment by jakebeal** [comment] 2018-01-21 03:40
@lisatiberio This is the same issue as in #111 : it's clearly reproducible and occurring in more datasets, so I'm bumping it back up to top triage, since it's now affecting multiple people.

**Comment by jakebeal** [comment] 2018-01-21 03:47
@bhwein @mjbrenner This bug does not appear to be affecting the computed conversion factors, only the reporting of peak numbers, so you should be safe to continue using these color models while we patch it.

**Comment by jakebeal** [comment] 2018-01-21 04:24
@lisatiberio I have added a test that reproduces this bug into branch fix/beadIDs-bug134, making use of a new bead file added to the examples in the tutorial repo. 

The problem appears to be linked to the handling of initial blank cells bead catalog: we are compensating for initial blanks in our numbering even when they are not there.  Thus, all the prior tests passed, since they were for RCP-30-5A in channels with an initial blank --- but without the blank we get this bug.

**Comment by lisatiberio** [comment] 2018-01-22 20:48
Pushed a fix to the server.  Added a pull request.

**Closed** 2018-01-30 13:54 UTC
Labels: Triage 0, bug, mathematics

**Comment by jakebeal** [comment] 2018-01-30 15:18
@bhwein @mjbrenner If you have a chance, it would be good to confirm that you are not seeing this issue any more either.

**Comment by mjbrenner** [comment] 2018-01-30 20:50
This issue appears to be fixed on the develop branch, although I had to change
CM=resolve(CM, settings);
to
CM=resolve(CM,);
and plots now dump directly into the color model folder instead of the subfolder 'plots'.

**Comment by jakebeal** [comment] 2018-01-30 21:30
Losing the settings was expected; we've been merging OutputSettings into TASBEConfig. The plots going to the wrong space was not expected.

Can you please check again? I believe that I have now fixed the defaulting.
