### ISSUE TITLE
Excel progress bar?

### ISSUE THREAD

**Issue by jakebeal** [TASBE/TASBEFlowAnalytics#285] opened 2018-07-13 16:51 UTC
Can we show some sort of progress bar for how far the Matlab session has run when running in Excel?

**Comment by coverney** [comment] 2018-08-11 20:32
Great news!! I was able to get this working for the Calibration tab, and I have an idea for the Cancel button. Things are looking very bright!

**Comment by coverney** [comment] 2018-08-12 14:15
I implemented multithreading for the other analysis functions and refined the progress bar. This feature is basically complete, but I won't close this issue until I give a demo.

**Comment by coverney** [comment] 2018-08-12 14:45
Also, I plan to do some more testing tomorrow morning.

**Comment by coverney** [comment] 2018-08-14 01:14
Completed first pass for this issue. It is ready for user input/testing. Changes are in next pull request (339). There are still some rare cases when the final msgbox doesn't appear, but I was not able to identify the cause.

**Closed by coverney** 2018-08-14 01:14 UTC
Labels: Triage 0, enhancement, user-interface
