### ISSUE TITLE
Implement non-numeric tuning parameters, such as strings

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#53] opened 2017-09-21 16:04 UTC

**Comment by jakebeal** [comment] 2017-09-22 11:34
Can you please explain more what you are thinking about for this issue?

**Comment by bhwein** [comment] 2017-09-25 04:25
I'm not sure what I was really thinking about this. I think I was thinking more on the lines of issue #55 that I posted. Basically where a device has many input conditions rather than a simple +/-, but not necessarily a dose response.

**Comment by jakebeal** [comment] 2017-09-25 09:12
For now, then, I'm going to close this as duplicate of #55. Please feel free to add additional information or re-open if additional distinctions arise.

**Closed by jakebeal** 2017-09-25 09:12 UTC
Labels: duplicate
