### ISSUE TITLE
Encountered an error on fca_read

### ISSUE THREAD

**Issue by georgebzheng** [TASBE/TASBEFlowAnalytics#432] opened 2019-04-03 20:50 UTC
When running against the latest in develop, I ran into the following error.  This used to work in commit c4247bd8a306ef3d122f7e507f7832bc53586b8d:

Traceback (most recent call last):
  File "/src/fcs.py", line 142, in <module>
    main(args)
  File "/src/fcs.py", line 112, in main
    color_model.make_color_model()
  File "/src/color_model.py", line 132, in make_color_model
    self.octave.eval('cm=resolve(cm);')
  File "/usr/local/lib/python3.6/dist-packages/oct2py/core.py", line 484, in eval
    plot_res=plot_res)
  File "/usr/local/lib/python3.6/dist-packages/oct2py/core.py", line 369, in feval
    store_as=store_as, plot_dir=plot_dir)
  File "/usr/local/lib/python3.6/dist-packages/oct2py/core.py", line 568, in _feval
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: 'fca_read' undefined near line 19 column 22
error: called from:
    resolve at line 19, column 20

**Comment by jakebeal** [comment] 2019-04-03 21:11
I've been unable to reproduce this issue. Can you please attach configuration information?

**Comment by georgebzheng** [comment] 2019-04-03 21:15
Here is the color model config file:

{
    "_comment1": "Parameters controlling conversion of process controls into an ERF color model, plus debugging/graphical outputs, to be supplied by TA1/TA2",
    "tasbe_color_model_parameters": {
        "_comment1": "the rdf:about field is a URI that persistently identifies this run configuration",
        "rdf:about": "placeholder",
        "TASBEConfig": {
            "sizebeads": {
                "rangeMin": 7,
                "rangeMax": 9.28,
                "peakThreshold": 1500,
                "forceFirstPeak": 1,
                "plotSize": [12, 8]
            },
            "beads": {
                "rangeMin": 6,
                "rangeMax": 10,
                "peakThreshold": 1000,
                "plotSize": [12, 8]
            },
            "heatmapPlottype": "contour",
            "plots": {
                "plotPath": "plots",
                "graphPlotSize": [12, 8]
            }
        },
        "_comment2": "Compatible TASBE interface version, following Semantic Versioning (semver.org).  Note that underspecifying version allows use of backward compatible upgrades.",
        "tasbe_version": "https://github.com/SD2E/reactors-etl/releases/tag/2",
        "_comment3": "identifier linking to the process control data set to be run",
        "process_control_data": "placeholder",
        "_comment4": "For each channel, the species and how to process and display it",
        "channel_parameters": [
            {
                "_comment1": "name must match a channel from the cytometer configuration",
                "name": "FSC 488/10-A",
                "_comment2": "a persistent URI linking to the actual species being quantified",
                "species": "https://www.ncbi.nlm.nih.gov/protein/AMZ00011.1",
                "_comment3": "Nickname for the species for charts",
                "label": "FSC 488/10-A",
                "_comment4": "cutoff for analysis",
                "min": 2,
                "_comment5": "primary color for lines on certain plots",
                "chart_color": "k"
            },
            {
                "_comment1": "name must match a channel from the cytometer configuration",
                "name": "SSC 488/10-A",
                "_comment2": "a persistent URI linking to the actual species being quantified",
                "species": "https://www.ncbi.nlm.nih.gov/protein/AMZ00011.1",
                "_comment3": "Nickname for the species for charts",
                "label": "SSC 488/10-A",
                "_comment4": "cutoff for analysis",
                "min": 2,
                "_comment5": "primary color for lines on certain plots",
                "chart_color": "b"
            },
            {
                "_comment1": "name must match a channel from the cytometer configuration",
                "name": "YFP-A",
                "_comment2": "a persistent URI linking to the actual species being quantified",
                "species": "https://www.ncbi.nlm.nih.gov/protein/AMZ00011.1",
                "_comment3": "Nickname for the species for charts",
                "label": "YFP-A",
                "_comment4": "cutoff for analysis",
                "min": 2,
                "_comment5": "primary color for lines on certain plots",
                "chart_color": "g"
            }
        ],
        "_comment5": "Other processing parameters, to be exposed",
        "tasbe_config": {
            "gating": {
                "type": "auto",
                "k_components": 2
            },
            "autofluorescence": {
                "type": "placeholder"
            },
            "compensation": {
                "type": "placeholder"
            },
            "beads": {
                "type": "placeholder"
            }
        },
        "_comment6": "Cutoff for bead peak detection",
        "bead_min": 2,
        "_comment7": "Which channel is being used for unit calibration",
        "ERF_channel_name": "YFP-A",
        "_comment8": "additional parameters controlling data processing and output",
        "translation_plot": false,
        "noise_plot": false
    }
}

**Comment by jakebeal** [comment] 2019-04-03 22:15
Fixed by #433 .

**Comment by jakebeal** [comment] 2019-04-04 13:59
... or maybe not; now there appears to be a new issue.

**Comment by jakebeal** [comment] 2019-04-04 20:46
Fixed by #435, confirmed by @georgebzheng

**Closed by jakebeal** 2019-04-04 20:46 UTC
