### ISSUE TITLE
Data getting cutoff around 1.5*10^8 CFP MEFL?

### ISSUE THREAD

**Issue by bhwein** [TASBE/TASBEFlowAnalytics#70] opened 2017-09-28 04:27 UTC
It seems my data is now getting cutoff at around 1.5*10^8 CFP MEFL using the latest code. Any ideas why?
<img width="893" alt="untitled 9" src="https://user-images.githubusercontent.com/28678480/30949320-ae56571a-a3e3-11e7-9945-9e819d2ecf76.png">
<img width="892" alt="untitled 10" src="https://user-images.githubusercontent.com/28678480/30949351-cba6bbde-a3e3-11e7-9bdb-8ae3ed8cbc84.png">

**Comment by jakebeal** [comment] 2017-09-28 10:48
I'm assuming this is the dataset in "20170910 BenWeinberg GIB-RAP-ABA Flps Dose Response".

Looking into it, the issue appear to be in building the gates, and this is one of those cases where I am amazed that it ever actually produced the results you saw before.  Here's what's happening: much of your FSC/SSC is saturated:
<img width="360" alt="blank-fscssc" src="https://user-images.githubusercontent.com/10675899/30962460-678d5898-a40f-11e7-9971-cfa12e8682c6.png">
The GMMGating system is set to by default ignore saturated FSC/SSC values in building its gate, as those can significantly distort the fitting process. There is some variability in the GMM fitting process (by default, the library starts with a randomized sample), and it looks like in your previous run the gate happened to end up stretched just far enough to cover the saturated values.  Those saturated FSC/SSC events, in turn, happen to include almost all of the highest values of BFP.
<img width="360" alt="gib -fscbfp" src="https://user-images.githubusercontent.com/10675899/30962665-3fc0559e-a410-11e7-9be4-4d26510f09b5.png">

You might thus be able to force the gate to include the saturated by changing the AutogateParameters `fraction` argument to include the whole range, rather than excluding saturated FSC/SSC in building the gate.  But should you?

It is not clear: is that FSC/SSC saturated material legitimate values at all, or is it multi-clumps that should be ignored? It would be good to adjust your FSC/SSC voltage settings for the future so that it is not saturated, and a more principled judgement can be made on whether to include or exclude it.

**Comment by bhwein** [comment] 2017-09-28 19:09
I'm actually using a very low FSC voltage (80). I'm not sure how much I want to turn this down. This is interesting that there are potentially many cells I am not looking at though. However, this was not a problem before you changed the code. This is the same exact data set. I'm just wondering why I cannot reach higher CFP MEFL units anymore. I'm wondering if something changed with the color translation, because my CFP MEFL values easily went up to 10^9/10^10 MEFL.

**Comment by jakebeal** [comment] 2017-09-28 19:29
My first suspicion was that this was an effect of minor variations in the GMM fit, but I just ran a few iterations, and saw now significant change that would allow the "faraway" material to be included.  

What was the version that you got the longer range from? I don't see any change that could account for this difference between 2.0.0 and 2.0.1, and your own code would have to have changed from 1.3.0-beta to 2.x.  If you ran it with 1.3.0-beta, do you have a diff of the current and prior code?

**Comment by jakebeal** [comment] 2018-07-01 21:53
I am unable to reproduce this error, and so am closing it as likely obsolete; if this issue recurs, please reopen with more information on how to reproduce.

**Closed by jakebeal** 2018-07-01 21:53 UTC
Labels: bug, mathematics, question
